version: '3'

services:
  web-server:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_files:/static_files
    networks:
      - base-network

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - base-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - base-network
    depends_on:
      - postgres

networks:
  base-network:
    driver: bridge

